package com.smartpark.api.shared.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    // Core
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    BUSINESS_ERROR("BUSINESS_ERROR"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    RESOURCE_CONFLICT("RESOURCE_CONFLICT"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
    INVALID_INPUT("INVALID_INPUT"),
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),

    // Vehicle
    VEHICLE_NOT_FOUND("VEHICLE_NOT_FOUND"),
    VEHICLE_ALREADY_EXISTS("VEHICLE_ALREADY_EXISTS"),
    VEHICLE_NOT_PARKED("VEHICLE_NOT_PARKED"),
    VEHICLE_ALREADY_PARKED("VEHICLE_ALREADY_PARKED"),

    // Parking Lot
    PARKING_LOT_NOT_FOUND("PARKING_LOT_NOT_FOUND"),
    PARKING_LOT_ALREADY_EXISTS("PARKING_LOT_ALREADY_EXISTS"),
    PARKING_LOT_FULL("PARKING_LOT_FULL");

    private final String value;
}